# Generated by Django 4.1.7 on 2023-05-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_id', models.CharField(max_length=250)),
                ('broker_name', models.CharField(max_length=250)),
                ('broker_logo', models.CharField(default='', max_length=250, null=True)),
                ('created_date', models.DateTimeField(null=True)),
                ('updated_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='brokers',
        ),
    ]
