# Generated by Django 4.1.7 on 2023-05-02 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_broker_delete_brokers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broker',
            name='broker_id',
        ),
    ]
