# Generated by Django 4.1.7 on 2023-05-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(blank=True, max_length=250, null=True)),
                ('strategy_type', models.CharField(default='', max_length=250, null=True)),
                ('status', models.CharField(default='', max_length=250)),
                ('created_date', models.DateTimeField(null=True)),
                ('updated_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
