# Generated by Django 4.1.7 on 2023-05-02 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_strategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Zerodha_UserID', models.CharField(default='', max_length=250, null=True)),
                ('Zerodha_Password', models.CharField(default='', max_length=250, null=True)),
                ('Zerodha_TOTP_Key', models.CharField(default='', max_length=250, null=True)),
                ('IIFL_Email_id', models.CharField(default='', max_length=250, null=True)),
                ('IIFL_Contact_Number', models.CharField(default='', max_length=250, null=True)),
                ('IIFL_App_Source', models.CharField(default='', max_length=250, null=True)),
                ('IIFL_User_Key', models.CharField(default='', max_length=250, null=True)),
                ('IIFL_User_id', models.CharField(default='', max_length=250, null=True)),
                ('IIFL_Password', models.CharField(default='', max_length=250, null=True)),
                ('IIFL_Encry_Key', models.CharField(default='', max_length=250, null=True)),
                ('IIFL_OcpApimSubscription', models.CharField(default='', max_length=250, null=True)),
                ('IIFL_My2Pin', models.CharField(default='', max_length=250, null=True)),
                ('IIFL_ClientCode', models.CharField(default='', max_length=250, null=True)),
                ('IIFL_cpass', models.CharField(default='', max_length=250, null=True)),
                ('Kotak_Key', models.CharField(default='', max_length=250, null=True)),
                ('Kotak_Secret', models.CharField(default='', max_length=250, null=True)),
                ('TA_Status', models.CharField(default='', max_length=250, null=True)),
                ('TA_Created_Date', models.CharField(default='', max_length=250, null=True)),
                ('Created_By', models.CharField(default='', max_length=250, null=True)),
                ('Updated_Date', models.CharField(default='', max_length=250, null=True)),
                ('Updated_By', models.CharField(default='', max_length=250, null=True)),
                ('BrokerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.broker')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
    ]
