# Generated by Django 4.1.7 on 2023-05-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_tradingaccount_brokerid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='created_date',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='updated_date',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='created_date',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='updated_date',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_date',
            field=models.CharField(default='', max_length=250, null=True),
        ),
    ]
