# Generated by Django 4.1.7 on 2023-05-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_broker_created_date_alter_broker_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='created_date',
            field=models.DateTimeField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='updated_date',
            field=models.DateTimeField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='created_date',
            field=models.DateTimeField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='updated_date',
            field=models.DateTimeField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_date',
            field=models.DateTimeField(default='', null=True),
        ),
    ]
