# Generated by Django 4.1.7 on 2023-05-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_broker_created_date_alter_broker_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='created_date',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='broker',
            name='updated_date',
            field=models.DateTimeField(default=''),
        ),
    ]
