# Generated by Django 4.2 on 2023-06-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_id', models.CharField(default='', max_length=50, null=True)),
                ('strategy_name', models.CharField(default='', max_length=50, null=True)),
                ('applicable_scripts', models.CharField(default='', max_length=50, null=True)),
                ('strategy_status', models.CharField(default='', max_length=50, null=True)),
                ('updated_by', models.CharField(default='', max_length=50, null=True)),
                ('updated_on', models.CharField(default='', max_length=50, null=True)),
                ('orb_range_candle_time', models.CharField(default='', max_length=50, null=True)),
                ('or_breakout_candle_time', models.CharField(default='', max_length=50, null=True)),
                ('orb_ma_h', models.CharField(default='', max_length=50, null=True)),
                ('orb_ma_l', models.CharField(default='', max_length=50, null=True)),
                ('orb_range_start_time', models.CharField(default='', max_length=50, null=True)),
                ('orb_retracement_time', models.CharField(default='', max_length=50, null=True)),
                ('itm_ma_h', models.CharField(default='', max_length=50, null=True)),
                ('itm_ma_l', models.CharField(default='', max_length=50, null=True)),
                ('itm_ma_oi', models.CharField(default='', max_length=50, null=True)),
                ('itm_reentry_after_mins', models.CharField(default='', max_length=50, null=True)),
                ('itm_entry_points_difference', models.CharField(default='', max_length=50, null=True)),
                ('itm_exit_points_difference', models.CharField(default='', max_length=50, null=True)),
                ('itm_sl_points_difference', models.CharField(default='', max_length=50, null=True)),
                ('itm_sl_cost_points_difference', models.CharField(default='', max_length=50, null=True)),
                ('itm_vwap_points_difference', models.CharField(default='', max_length=50, null=True)),
                ('itm_sold_option_premium_decay', models.CharField(default='', max_length=50, null=True)),
                ('itm_profit_percent', models.CharField(default='', max_length=50, null=True)),
                ('itm_profit_increment', models.CharField(default='', max_length=50, null=True)),
                ('itm_first_target_qty', models.CharField(default='', max_length=50, null=True)),
                ('itm_second_target_qty', models.CharField(default='', max_length=50, null=True)),
                ('itm_order_type', models.CharField(default='', max_length=50, null=True)),
                ('itm_last_entry_condition_check_time', models.CharField(default='', max_length=10, null=True)),
                ('itm_pyramid_start_time', models.CharField(default='', max_length=100, null=True)),
                ('itm_last_pyramid_condition_check_time', models.DateTimeField(default='', max_length=20, null=True)),
                ('itm_second_tranche_time_diffence_mins', models.CharField(default='', max_length=20, null=True)),
                ('itm_order_qty', models.CharField(default='', max_length=20, null=True)),
                ('itm_order_multiplier', models.CharField(default='', max_length=20, null=True)),
                ('nifty_instrument_token', models.CharField(default='', max_length=20, null=True)),
                ('nifty_hl_difference_points', models.CharField(default='', max_length=20, null=True)),
                ('nifty_or_range_point_difference', models.CharField(default='', max_length=20, null=True)),
                ('nifty_or_breakout_range_point_diff', models.CharField(default='', max_length=20, null=True)),
                ('bankNifty_instrument_token', models.CharField(default='', max_length=20, null=True)),
                ('bankNifty_hl_difference_points', models.CharField(default='', max_length=20, null=True)),
                ('bankNifty_or_range_point_difference', models.CharField(default='', max_length=20, null=True)),
                ('bankNifty_or_breakout_range_point_diff', models.CharField(default='', max_length=20, null=True)),
                ('finNifty_instrument_token', models.CharField(default='', max_length=20, null=True)),
                ('finNifty_hl_difference_points', models.CharField(default='', max_length=20, null=True)),
                ('finNifty_or_range_point_difference', models.CharField(default='', max_length=20, null=True)),
                ('finNifty_or_breakout_range_point_diff', models.CharField(default='', max_length=20, null=True)),
            ],
        ),
    ]
