# Generated by Django 4.2.1 on 2023-06-13 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_name', models.CharField(max_length=250)),
                ('broker_logo', models.CharField(default='', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orb_range_candle_time', models.CharField(default='', max_length=50, null=True)),
                ('or_breakout_candle_time', models.CharField(default='', max_length=50, null=True)),
                ('orb_ma_h', models.CharField(default='', max_length=10, null=True)),
                ('orb_ma_l', models.CharField(default='', max_length=100, null=True)),
                ('orb_range_start_time', models.DateTimeField(default='', max_length=20, null=True)),
                ('orb_retracement_time', models.CharField(default='', max_length=20, null=True)),
                ('hl_difference_points', models.CharField(default='', max_length=20, null=True)),
                ('ttoken', models.CharField(default='', max_length=20, null=True)),
                ('moving_avg_rows', models.CharField(default='', max_length=20, null=True)),
                ('or_breakout_range_point_diff', models.CharField(default='', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(blank=True, max_length=250, null=True)),
                ('strategy_type', models.CharField(default='', max_length=250, null=True)),
                ('status', models.CharField(default='', max_length=250)),
                ('created_date', models.DateTimeField(default='', null=True)),
                ('updated_date', models.DateTimeField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.CharField(default='', max_length=250, null=True)),
                ('contact_no', models.CharField(max_length=250)),
                ('user_password', models.CharField(max_length=250)),
                ('status', models.CharField(default='', max_length=250)),
                ('created_date', models.DateTimeField(default='', null=True)),
                ('updated_date', models.DateTimeField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Zerodha_UserID', models.CharField(default='', max_length=250, null=True)),
                ('Zerodha_Password', models.CharField(default='', max_length=250, null=True)),
                ('Zerodha_TOTP_Key', models.CharField(default='', max_length=250, null=True)),
                ('IIFL_Email_id', models.CharField(default='', max_length=250, null=True)),
                ('IIFL_Contact_Number', models.CharField(default='', max_length=250, null=True)),
                ('IIFL_App_Source', models.CharField(default='', max_length=250, null=True)),
                ('IIFL_User_Key', models.CharField(default='', max_length=250, null=True)),
                ('IIFL_User_id', models.CharField(default='', max_length=250, null=True)),
                ('IIFL_Password', models.CharField(default='', max_length=250, null=True)),
                ('IIFL_Encry_Key', models.CharField(default='', max_length=250, null=True)),
                ('IIFL_OcpApimSubscription', models.CharField(default='', max_length=250, null=True)),
                ('IIFL_My2Pin', models.CharField(default='', max_length=250, null=True)),
                ('IIFL_ClientCode', models.CharField(default='', max_length=250, null=True)),
                ('IIFL_cpass', models.CharField(default='', max_length=250, null=True)),
                ('Kotak_Key', models.CharField(default='', max_length=250, null=True)),
                ('Kotak_Secret', models.CharField(default='', max_length=250, null=True)),
                ('TA_Status', models.CharField(default='', max_length=250, null=True)),
                ('TA_Created_Date', models.CharField(default='', max_length=250, null=True)),
                ('Created_By', models.CharField(default='', max_length=250, null=True)),
                ('Updated_Date', models.CharField(default='', max_length=250, null=True)),
                ('Updated_By', models.CharField(default='', max_length=250, null=True)),
                ('BrokerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.broker')),
                ('UserID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
    ]
