# Generated by Django 4.2 on 2023-06-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='created_date',
            field=models.DateTimeField(default='', null=True),
        ),
    ]
