# Generated by Django 4.2 on 2023-06-16 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_broker_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broker',
            name='created_date',
        ),
    ]
