from django.db import models

# class Broker(models.Model):
#     timeid = models.CharField(max_length=255,default="",null=True)
#     broker_name=models.CharField(max_length=250)
#     broker_logo=models.CharField(max_length=250,default="",null=True) 
#     created_date=models.CharField(max_length=200,null=True,default="")
#     # updated_date=models.DateTimeField(null=True,default="")
        
# class user(models.Model):
#     user_name=models.CharField(max_length=250 ,blank=True ,null=True)
#     email=models.CharField(max_length=250,default="",null=True) 
#     contact_no=models.CharField(max_length=250)
#     user_password=models.CharField(max_length=250)
#     status=models.CharField(max_length=250, default="")
#     created_date=models.DateTimeField(null=True,default="")
#     updated_date=models.DateTimeField(null=True,default="")
        
# class strategy(models.Model):
#     strategy_name=models.CharField(max_length=250 ,blank=True ,null=True)
#     strategy_type=models.CharField(max_length=250,default="",null=True) 
#     status=models.CharField(max_length=250, default="")
#     created_date=models.DateTimeField(null=True,default="")
#     updated_date=models.DateTimeField(null=True,default="")
        
# class TradingAccount(models.Model):
#     UserID = models.ForeignKey(user, on_delete=models.CASCADE, null=True)
#     BrokerID = models.ForeignKey(Broker, on_delete=models.CASCADE, null=True)
#     Zerodha_UserID = models.CharField(max_length=250,null=True,default="")
#     Zerodha_Password = models.CharField(max_length=250,null=True,default="")
#     Zerodha_TOTP_Key = models.CharField(max_length=250,null=True,default="")
#     IIFL_Email_id = models.CharField(max_length=250,null=True,default="")
#     IIFL_Contact_Number = models.CharField(max_length=250,null=True,default="")
#     IIFL_App_Source = models.CharField(max_length=250,null=True,default="")
#     IIFL_User_Key = models.CharField(max_length=250,null=True,default="")
#     IIFL_User_id = models.CharField(max_length=250,null=True,default="")
#     IIFL_Password = models.CharField(max_length=250,null=True,default="")
#     IIFL_Encry_Key = models.CharField(max_length=250,null=True,default="")
#     IIFL_OcpApimSubscription = models.CharField(max_length=250,null=True,default="")
#     IIFL_My2Pin = models.CharField(max_length=250,null=True,default="")
#     IIFL_ClientCode = models.CharField(max_length=250,null=True,default="")
#     IIFL_cpass = models.CharField(max_length=250,null=True,default="")
#     Kotak_Key = models.CharField(max_length=250,null=True,default="")
#     Kotak_Secret = models.CharField(max_length=250,null=True,default="")
#     TA_Status = models.CharField(max_length=250,null=True,default="")
#     TA_Created_Date = models.CharField(max_length=250,null=True,default="")
#     Created_By = models.CharField(max_length=250,null=True,default="")
#     Updated_Date = models.CharField(max_length=250,null=True,default="")
#     Updated_By = models.CharField(max_length=250,null=True,default="")


class Strategy(models.Model):
    strategy_id=models.CharField(max_length=50,null=True,default="")
    strategy_name=models.CharField(max_length=50,null=True,default="")
    applicable_scripts=models.CharField(max_length=50,null=True,default="")
    strategy_status=models.CharField(max_length=50,null=True,default="")
    updated_by=models.CharField(max_length=50,null=True,default="")
    updated_on=models.CharField(max_length=50,null=True,default="")
    orb_range_candle_time=models.CharField(max_length=50,null=True,default="")
    or_breakout_candle_time=models.CharField(max_length=50,null=True,default="")
    orb_ma_h=models.CharField(max_length=50,null=True,default="")
    orb_ma_l=models.CharField(max_length=50,null=True,default="")
    orb_range_start_time=models.CharField(max_length=50,null=True,default="")
    orb_retracement_time=models.CharField(max_length=50,null=True,default="")
    itm_ma_h=models.CharField(max_length=50,null=True,default="")
    itm_ma_l=models.CharField(max_length=50,null=True,default="")
    itm_ma_oi=models.CharField(max_length=50,null=True,default="")
    itm_reentry_after_mins=models.CharField(max_length=50,null=True,default="")
    itm_entry_points_difference=models.CharField(max_length=50,null=True,default="")
    itm_exit_points_difference=models.CharField(max_length=50,null=True,default="")
    itm_sl_points_difference=models.CharField(max_length=50,null=True,default="")
    itm_sl_cost_points_difference=models.CharField(max_length=50,null=True,default="")
    itm_vwap_points_difference=models.CharField(max_length=50,null=True,default="")
    itm_sold_option_premium_decay=models.CharField(max_length=50,null=True,default="")
    itm_profit_percent=models.CharField(max_length=50,null=True,default="")
    itm_profit_increment=models.CharField(max_length=50,null=True,default="")
    itm_first_target_qty=models.CharField(max_length=50,null=True,default="")
    itm_second_target_qty=models.CharField(max_length=50,null=True,default="")
    itm_order_type=models.CharField(max_length=50,null=True,default="")
    itm_last_entry_condition_check_time=models.CharField(max_length=10,null=True,default="")
    itm_pyramid_start_time=models.CharField(max_length=100,null=True,default="")
    itm_last_pyramid_condition_check_time = models.DateTimeField(max_length=20,null=True,default="")
    itm_second_tranche_time_diffence_mins = models.CharField(max_length=20,null=True,default="")
    itm_order_qty = models.CharField(max_length=20,null=True,default="")
    itm_order_multiplier = models.CharField(max_length=20,null=True,default="")
    nifty_instrument_token = models.CharField(max_length=20,null=True,default="")
    nifty_hl_difference_points = models.CharField(max_length=20,null=True,default="")
    nifty_or_range_point_difference = models.CharField(max_length=20,null=True,default="")
    nifty_or_breakout_range_point_diff = models.CharField(max_length=20,null=True,default="")
    bankNifty_instrument_token = models.CharField(max_length=20,null=True,default="")
    bankNifty_hl_difference_points = models.CharField(max_length=20,null=True,default="")
    bankNifty_or_range_point_difference = models.CharField(max_length=20,null=True,default="")
    bankNifty_or_breakout_range_point_diff = models.CharField(max_length=20,null=True,default="")
    finNifty_instrument_token = models.CharField(max_length=20,null=True,default="")
    finNifty_hl_difference_points = models.CharField(max_length=20,null=True,default="")
    finNifty_or_range_point_difference = models.CharField(max_length=20,null=True,default="")
    finNifty_or_breakout_range_point_diff = models.CharField(max_length=20,null=True,default="")

